# High-Frequency Trading Analytics Configuration
# Author: Gabriel Demetrios Lafis

# Environment settings
environment: development

# Trading parameters
trading:
  initial_capital: 1000000
  commission: 0.0007
  slippage: 0.0002
  max_position_size: 100000
  risk_per_trade: 0.02

# Data settings
data:
  raw_path: data/raw/
  processed_path: data/processed/
  features_file: features.parquet
  
# Model parameters
models:
  random_seed: 42
  train_test_split: 0.8
  validation_split: 0.1
  
# Backtesting settings
backtesting:
  start_date: "2025-01-01"
  end_date: "2025-12-31"
  benchmark: "SPY"
  
# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/trading.log
